logo: /assets/SquareIcon.png

plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-polyglot
  - jekyll-include-cache

remote_theme: hydecorp/hydejack@v9.2.1

menu:
  en:
    - title: Download Android App
      url: https://github.com/kitswas/VirtualGamePad-Mobile/releases
    - title: Download PC Server
      url: https://github.com/kitswas/VirtualGamePad-PC/releases
    - title: View on GitHub
      url: https://github.com/kitswas/VirtualGamePad/
    - title: FAQ
      url: /FAQ.html
    - title: Troubleshooting
      url: /Troubleshooting.html
    - title: Contribute
      url: /Contributing.html
    - title: Roadmap
      url: /Roadmap.html
    - title: Privacy Policy
      url: /Privacy.html
  hi:
    - title: एंड्रॉइड ऐप डाउनलोड करें
      url: https://github.com/kitswas/VirtualGamePad-Mobile/releases
    - title: पीसी सर्वर डाउनलोड करें
      url: https://github.com/kitswas/VirtualGamePad-PC/releases
    - title: GitHub पर देखें
      url: https://github.com/kitswas/VirtualGamePad/
    - title: सामान्य प्रश्न
      url: /hi/FAQ.html
    - title: समस्या निवारण
      url: /hi/Troubleshooting.html
    - title: योगदान करें
      url: /hi/Contributing.html
    - title: रोडमैप
      url: /hi/Roadmap.html
    - title: गोपनीयता नीति
      url: /hi/Privacy.html
  bn:
    - title: অ্যান্ড্রয়েড অ্যাপ ডাউনলোড করুন
      url: https://github.com/kitswas/VirtualGamePad-Mobile/releases
    - title: পিসি সার্ভার ডাউনলোড করুন
      url: https://github.com/kitswas/VirtualGamePad-PC/releases
    - title: GitHub-এ দেখুন
      url: https://github.com/kitswas/VirtualGamePad/
    - title: প্রশ্নাবলী
      url: /bn/FAQ.html
    - title: সমস্যা সমাধান
      url: /bn/Troubleshooting.html
    - title: অবদান রাখুন
      url: /bn/Contributing.html
    - title: রোডম্যাপ
      url: /bn/Roadmap.html
    - title: গোপনীয়তা নীতি
      url: /bn/Privacy.html

defaults:
  - scope:
      path: ""
    values:
      image: /assets/open-graph-image.png # Default social image
      accent_image: /assets/GamepadIcon.png
      accent_color: "#157878"

favicon: /favicon.ico

hydejack:
  # https://hydejack.com/blog/hydejack/2024-09-08-x-marks-the-spot-in-hydejack-9-2/
  # Starting with Hydejack 9.2, dark mode is included in all versions of Hydejack.
  dark_mode:
    # Set to `true` to always use the dark theme.
    always: false

    # Set to `true` to use the dark theme based on visitors' preference (OS setting).
    dynamic: true

    # Set to `true` to allow visitors to switch between light and dark mode.
    icon: true

# Internationalization (i18n) settings

languages:
  - en
  - hi
  - bn
default_lang: en

exclude_from_localizations:
  - assets
  - _includes
  - _config.yml
  - LICENCE.TXT

parallel_localization: true
url: https://kitswas.github.io/VirtualGamePad
